trigger:
- develop

pool: kiran
  # vmImage: ubuntu-latest

# steps:

# - task: Docker@2
#   inputs:
#     command: 'build'
#     Dockerfile: '**/Dockerfile'

# - task: AWSCLI@1
#   inputs:
#     awsCredentials: 'aws-cli'
#     regionName: 'us-east-1'
#     awsCommand: 'aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s1m8f5e6'
#     awsSubCommand: 'aws --version'
# - task: Docker@2
#   inputs:
#     command: 'buildAndPush'
#     Dockerfile: '**/Dockerfile'
variables:
   - group: dev
   - name: DOCKER_REPOSITORY
     value: public.ecr.aws/$(AWS_ACCOUNT_ID)/$(DOCKER_REPOSITORY_NAME)

steps:
- script: |
    aws ecr-public get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin public.ecr.aws/$(AWS_ACCOUNT_ID)
  displayName: 'Login to AWS'
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: Docker@2
  displayName: Build docker image
  inputs:
    repository: $(DOCKER_REPOSITORY)
    command: buildAndPush
    Dockerfile: Dockerfile
    tags: |
      latest
