apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
  labels:
     app: "{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
    spec:      
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      serviceAccountName: "{{ .Values.serviceAccount.name }}"
      containers:
        - name: {{ .Chart.Name }}
          image: 870608046950.dkr.ecr.us-east-1.amazonaws.com/myeks:117
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http