{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  - hosts:
        {{ .Values.host }}
      
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: {{ .Values.path }}
            backend:
              service:
                name: "{{ .Chart.Name }}"
                port:
                  number: {{ .Values.service.port }}
{{- end }}
